name: "Tests the App"
env:
  DB_URL: ${{ secrets.DB_URL }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Migrate the database
      run: npm run db:migrate
    - name: Seed the data
      run: npm run db:seed
    - name: Run unit tests
      run: npm run test
    - name: Run e2e tests
      run: npm run test:e2e
